Panels:
  - Class: rviz/Displays
    Help Height: 78
    Name: Displays
    Property Tree Widget:
      Expanded:
        - /Head Camera1
      Splitter Ratio: 0.65625
    Tree Height: 478
  - Class: rviz/Views
    Expanded:
      - /Current View1
    Name: Views
    Splitter Ratio: 0.5
  - Class: rviz/Time
    Name: Time
Visualization Manager:
  Class: ""
  Displays:
    - Alpha: 0.5
      Cell Size: 1
      Class: rviz/Grid
      Color: 160; 160; 164
      Enabled: true
      Line Style:
        Line Width: 0.03
        Value: Lines
      Name: Grid
      Normal Cell Count: 0
      Offset:
        X: 0
        Y: 0
        Z: 0
      Plane: XY
      Plane Cell Count: 10
      Reference Frame: <Fixed Frame>
      Value: true
    - Alpha: 1
      Class: rviz/RobotModel
      Collision Enabled: false
      Enabled: true
      Links:
        {}
      Name: Robot Model
      Robot Description: robot_description
      TF Prefix: ""
      Update Interval: 0
      Value: true
      Visual Enabled: true
    - Class: rviz/InteractiveMarkers
      Enabled: true
      Name: PR2 Teleop
      Show Axes: false
      Show Descriptions: true
      Update Topic: /pr2_marker_control/update
      Value: true
    - Class: rviz/InteractiveMarkers
      Enabled: true
      Name: Pick Up Objects
      Show Axes: false
      Show Descriptions: true
      Update Topic: /interactive_manipulation/update
      Value: true
    - Class: rviz/InteractiveMarkers
      Enabled: true
      Name: Snapshot
      Show Axes: false
      Show Descriptions: true
      Update Topic: /interactive_point_cloud/update
      Value: true
    - Class: pr2_interactive_manipulation_frontend/PublishClickCamera
      Enabled: true
      Image Rendering: background
      Image Topic: /interactive_manipulation_camera/image
      Name: Head Camera
      Near Clip Distance: 0.35
      Overlay Alpha: 0.5
      Publish Click Topic: /interactive_manipulation_image_click
      Queue Size: 2
      Transport Hint: compressed
      Value: true
      Visibility:
        Debug Displays:
          Attached Objects: true
          Base Laser: true
          Grasp Execution Markers: true
          Grasp Markers: true
          Map: true
          Nav Global Path: true
          Nav Obstacles: true
          Octomap Point Cloud: true
          Planning Scene Markers: true
          Tabletop Segmentation Markers: true
          Value: true
        Grid: false
        Kinect Stream: false
        PR2 Teleop: false
        Panels:
          CameraFocusFrontend: true
          Manipulation: true
          Object Detection: true
          Object Recognition: true
          Value: true
        People Tracking:
          InteractiveMarkers: true
          Value: true
        Pick Up Objects: true
        Robot Model: false
        Snapshot: false
        Value: true
      Zoom Factor: 1
    - Alpha: 1
      Autocompute Intensity Bounds:
        Max Intensity: 4096
        Min Intensity: 0
        Value: true
      Autocompute Value Bounds:
        Max Value: 10
        Min Value: -10
        Value: true
      Axis: Z
      Channel Name: intensity
      Class: rviz/DepthCloud
      Color: 255; 255; 255
      Color Image Topic: /head_mount_kinect/rgb/image_color
      Color Transformer: RGB8
      Color Transport Hint: compressed
      Decay Time: 0
      Depth Map Topic: /head_mount_kinect/depth/image
      Depth Map Transport Hint: compressedDepth
      Enabled: false
      Name: Kinect Stream
      Position Transformer: XYZ
      Queue Size: 3
      Selectable: true
      Size (Pixels): 3
      Size (m): 0.005
      Style: Spheres
      Topic Filter: true
      Use Fixed Frame: true
      Use rainbow:
        Max Color: 255; 255; 255
        Min Color: 0; 0; 0
        Value: true
      Value: false
    - Class: rviz/Group
      Displays:
        - Class: object_recognition_gui/ObjectRecognition
          Enabled: true
          Name: Object Recognition
        - Class: pr2_interactive_manipulation_frontend/InteractiveManipulationFrontend
          Enabled: true
          Name: Manipulation
        - Class: pr2_interactive_object_detection/InteractiveObjectDetection
          Enabled: true
          Name: Object Detection
        - Class: pr2_interactive_manipulation_frontend/CameraFocusFrontend
          Command topic: /rviz/camera_placement
          Enabled: true
          Name: CameraFocusFrontend
          Value: true
      Enabled: true
      Name: Panels
    - Class: rviz/Group
      Displays:
        - Class: rviz/Marker
          Enabled: true
          Marker Topic: /grasp_markers
          Name: Grasp Markers
          Namespaces:
            {}
          Queue Size: 100
          Value: true
        - Class: rviz/Marker
          Enabled: true
          Marker Topic: /object_manipulator/grasp_execution_markers
          Name: Grasp Execution Markers
          Namespaces:
            {}
          Queue Size: 100
          Value: true
        - Class: rviz/Marker
          Enabled: true
          Marker Topic: /attached_objects
          Name: Attached Objects
          Namespaces:
            {}
          Queue Size: 100
          Value: true
        - Class: rviz/Marker
          Enabled: true
          Marker Topic: /planning_scene_markers
          Name: Planning Scene Markers
          Namespaces:
            {}
          Queue Size: 100
          Value: true
        - Alpha: 1
          Autocompute Intensity Bounds:
            Max Intensity: 4096
            Min Intensity: 0
            Value: true
          Autocompute Value Bounds:
            Max Value: 2.8125
            Min Value: -0.0375
            Value: true
          Axis: Z
          Channel Name: intensity
          Class: rviz/PointCloud2
          Color: 255; 255; 255
          Color Transformer: FlatColor
          Decay Time: 0
          Enabled: true
          Name: Octomap Point Cloud
          Position Transformer: XYZ
          Queue Size: 10
          Selectable: true
          Size (Pixels): 3
          Size (m): 0.025
          Style: Boxes
          Topic: /octomap_point_cloud
          Use Fixed Frame: true
          Use rainbow:
            Max Color: 255; 255; 255
            Min Color: 0; 0; 0
            Value: true
          Value: true
        - Class: rviz/Marker
          Enabled: true
          Marker Topic: /tabletop_segmentation_markers
          Name: Tabletop Segmentation Markers
          Namespaces:
            {}
          Queue Size: 100
          Value: true
        - Alpha: 0.7
          Class: rviz/Map
          Draw Behind: false
          Enabled: true
          Name: Map
          Topic: /map
          Value: true
        - Alpha: 1
          Autocompute Intensity Bounds:
            Max Intensity: 4096
            Min Intensity: 0
            Value: true
          Autocompute Value Bounds:
            Max Value: 10
            Min Value: -10
            Value: true
          Axis: Z
          Channel Name: intensity
          Class: rviz/LaserScan
          Color: 255; 255; 255
          Color Transformer: Intensity
          Decay Time: 0
          Enabled: true
          Name: Base Laser
          Position Transformer: XYZ
          Queue Size: 10
          Selectable: true
          Size (Pixels): 3
          Size (m): 0.01
          Style: Billboards
          Topic: /base_scan_throttled
          Use Fixed Frame: true
          Use rainbow:
            Max Color: 255; 255; 255
            Min Color: 0; 0; 0
            Value: true
          Value: true
        - Alpha: 1
          Class: rviz/GridCells
          Color: 255; 255; 127
          Enabled: true
          Name: Nav Obstacles
          Topic: /move_base_node/local_costmap/obstacles
          Value: true
        - Alpha: 1
          Class: rviz/Path
          Color: 25; 255; 0
          Enabled: true
          Name: Nav Global Path
          Topic: /move_base_node/NavfnROS/plan
          Value: true
      Enabled: false
      Name: Debug Displays
    - Class: rviz/Group
      Displays:
        - Class: rviz/InteractiveMarkers
          Enabled: true
          Name: InteractiveMarkers
          Show Axes: false
          Show Descriptions: true
          Update Topic: ""
          Value: true
      Enabled: true
      Name: People Tracking
  Enabled: true
  Global Options:
    Background Color: 48; 48; 48
    Fixed Frame: /map
  Name: root
  Tools:
    - Class: rviz/Interact
    - Class: rviz/MoveCamera
  Value: true
  Views:
    Current:
      Class: rviz/Free
      Control Mode: Orbit
      Distance: 2.76985
      Eye:
        X: 0.249999
        Y: 2.63999
        Z: 0.799999
      Focus:
        X: 0.354845
        Y: -0.127871
        Z: 0.8
      Maintain Vertical Axis: true
      Mouse Enabled: true
      Name: Current View
      Near Clip Distance: 0.35
      Placement Topic: /rviz/camera_placement
      Target Frame: <Fixed Frame>
      Trajectory Topic: /rviz/camera_placement_trajectory
      Transition Time: 0.5
      Up:
        X: 0
        Y: 0
        Z: 1
      Value: Free (rviz)
    Saved: ~
Window Geometry:
  Height: 782
  Hide Left Dock: false
  Hide Right Dock: false
  QMainWindow State: 000000ff00000000fd00000003000000000000013e0000028bfc0200000006fc0000014e000000ad0000000000fffffffa000000000100000001fb000000300049006e0074006500720061006300740069007600650020004d0061006e006900700075006c006100740069006f006e0100000000ffffffff0000000000000000fb000000160048006500610064002000430061006d0065007200610100000041000001410000001600fffffffb00000018004d0061006e006900700075006c006100740069006f006e010000018800000144000000bd00fffffffb00000020004f0062006a00650063007400200044006500740065006300740069006f006e01000001eb000000bd0000000000000000fb0000000800540069006d0065020000028f00000446000002c700000046fb000000380049006e0074006500720061006300740069007600650020004f0062006a00650063007400200044006500740065006300740069006f006e0100000268000000cc000000000000000000000001000001220000028bfc0200000002fc000000410000028b000000fb0100001dfa000000010100000002fb0000000a005600690065007700730100000000ffffffff0000010f00fffffffb000000100044006900730070006c00610079007301000006080000011d0000010f00fffffffc00000041000003740000000000fffffffa000000000100000002fb0000001200530065006c0065006300740069006f006e0100000000ffffffff0000000000000000fb0000001e0054006f006f006c002000500072006f007000650072007400690065007300000006310000011d0000000000000000000000020000019a00000031fc0100000002fb0000001800430061006d00650072006100200046006f00630075007301000001440000019a0000000000000000fb0000002a00430061006d00650072006100200046006f006300750073002000460072006f006e00740065006e006401000001440000029c0000000000000000000001ba0000028b00000001000000020000000100000002fc00000003000000020000000000000002000000020000000a0054006f006f006c00730100000000ffffffff00000000000000000000001600430061006d0065007200610046006f0063007500730100000127ffffffff00000000000000000000000300000000
  Width: 1078
  X: 80
  Y: 39
